- name: create_pi_cientifico
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: tarea para crear tabla pi_cientifico
      community.postgresql.postgresql_table:
        db: postgres
        name: cientifico_metrics
        columns:
          - id serial
          - datname varchar
          - fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          - schema_name varchar
          - revision varchar
          - fk int
          - pk int
          - trigger int
          - varchar_all int
          - pk_no_num_unacolumn int
          - columnas_mas_64 int
          - pk_column_mas_3 int
        owner: "{{ pg_owner }}"
      when: inventory_hostname in primary
      become_user: "{{ pg_owner }}"
 
    - name: tarea para crear tabla pi_cientifico
      community.postgresql.postgresql_table:
        db: postgres
        name: cientifico_metrics_detalle
        columns:
          - id serial
          - datname varchar
          - fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          - schema_name varchar
          - table_name varchar
          - constraint_fk varchar
          - definicion varchar
          - table_without_pk boolean
          - trigger varchar
          - column_name_pknonumerica varchar
          - all_varchar int
          - num_clave_primaria int
          - num_columns_in_table int
          - pk_mas_3_cols varchar
          - column_name_varchar varchar
          - db_schema_table varchar
        owner: "{{ pg_owner }}"
      when: inventory_hostname in primary
      become_user: "{{ pg_owner }}"
 
    - name: tarea para crear tabla pi_cientifico_depurado
      community.postgresql.postgresql_table:
        db: postgres
        name: cientifico_metrics_depurado_date
        columns:
          - id serial
          - fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          - datname varchar
          - schema_name varchar
          - table_name varchar
          - depurado varchar
          - db_schema_table varchar
        owner: "{{ pg_owner }}"
      when: inventory_hostname in primary
      become_user: "{{ pg_owner }}"
     
    - name: tarea para crear tabla pi_cientifico_scan
      community.postgresql.postgresql_table:
        db: postgres
        name: cientifico_metrics_scan
        columns:
          - id serial
          - fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          - datname varchar
          - schema_name varchar
          - table_name varchar
          - seq_scan int
          - idx_scan int
          - porcentaje_idx_usado int
          - filas_en_tabla int
          - db_schema_table varchar
        owner: "{{ pg_owner }}"
      when: inventory_hostname in primary
      become_user: "{{ pg_owner }}"
 
    - name: grant privileges
      community.postgresql.postgresql_privs:
        db: postgres
        obj: "{{ item }}"
        type: table
        privs: SELECT
        role: pg_monitor
      when: inventory_hostname in primary
      become_user: "{{ pg_owner }}"
      with_items:
        - cientifico_metrics_depurado_date
        - cientifico_metrics_scan
        - cientifico_metrics
        - cientifico_metrics_detalle
